apiVersion: v1
kind: Service
metadata:
  name: user
  namespace: roboshop
  labels:
    component: user
    project: roboshop
    tier: app
spec:
  selector:
    component: user
    project: roboshop
    tier: app
  ports:
  - protocol: TCP
    port: 8080 #Service Port
    targetPort: 8080 #Container Port
